### ISSUE TITLE
About the medal in the corner

### ISSUE THREAD

**Issue by Scoutman01** [rbjaxter/budhud#334] opened 2020-06-11 17:14 UTC
For me it appear when i toggle the scorebard during the freezecams, maybe put medal_width to 0 may fix it ?

**Comment by rbjaxter** [comment] 2020-06-12 20:17
Has this happened to you recently? I haven't seen it happen in a long time, but that is an interesting theory. I'll try that out when I next play.

**Comment by Scoutman01** [comment] 2020-06-12 20:44
Yes everytime on casual

**Comment by rbjaxter** [comment] 2020-06-16 21:43
I'll close this for now since it's a duplicate of #307. I haven't been able to replicate the toggle scoreboard thing as of yet, but I'll keep messing with it. thanks for the tip :D

**Closed by rbjaxter** 2020-06-16 21:43 UTC
