### ISSUE TITLE
TF2 crashes on freezecam screen when compiled HUD is used

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#498] opened 2024-07-09 13:52 UTC

**Comment by rbjaxter** [comment] 2024-07-10 18:43
I'm not sure if I have this on my local copy, but it appears this may potentially be due to an extra closing brace: https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/freezepanel_basic.res#L106

I've found that, with using #base like I do, extra closing braces don't always break things...so it'd make sense that it would happen on compile. If you wanted to troubleshoot, I'd try removing that brace and then re-compiling to see if it still happens.

I'll check on my end as well. I may need to adjust the pin positioning and so forth once it is fixed

**Comment by qkeitoe** [comment] 2024-07-10 20:04
I decided to look in the compiled file (I didn't have time to do it right away and then somehow forgot about it) and realized that it must be the quotes around `#base` that cause bugs in the compiled file.
https://github.com/rbjaxter/budhud/blob/3bc2760cc8a6fed8d990afa64e407eec6eae8217/_budhud/resource/ui/freezepanel_basic.res#L1

The compiled file in the current version:
![image](https://github.com/rbjaxter/budhud/assets/66339491/db8d6767-322d-4bdd-9d08-54e583f64f6f)
The compiled file after the quotes removed:
![image](https://github.com/rbjaxter/budhud/assets/66339491/8058cb0c-7fae-4360-a959-def954280af8)

Is it how the freezecam screen supposed to look like?
![image](https://github.com/rbjaxter/budhud/assets/66339491/3e664fe4-3735-4b4e-8209-00010b3d5520)

If so, than removing the quotes solves the issue.

**Comment by rbjaxter** [comment] 2024-07-10 20:46
Ahh good catch, tbh I'm not sure how that got changed since I didn't add the quotes

@cooolbros https://raw.githubusercontent.com/rbjaxter/budhud/3bc2760cc8a6fed8d990afa64e407eec6eae8217/_budhud/resource/ui/freezepanel_basic.res

I downloaded this res file and remove the quotes around #base. When using "Format Document" again, it seems to add the quotes back around the #base include. Any ideas why?
<img width="618" alt="Code_qLo2dhRaVt" src="https://github.com/rbjaxter/budhud/assets/509599/90708f6b-427d-4119-b3a8-3b3843d13911">
<img width="618" alt="sF3MXDTr2N" src="https://github.com/rbjaxter/budhud/assets/509599/fdfa4cdf-3d5a-445d-a7f6-69bd6b8d3334">

**Comment by rbjaxter** [comment] 2024-07-10 20:48
May be user error tbh, I'm testing it on my work PC so I can't double-check with the budhud formatter (only have VSCode VDF on this PC). But I figured I'd check with you in case it happens to you as well

**Comment by qkeitoe** [comment] 2024-07-10 21:24
The same is happening on my end as well. I always thought there was an option in charge of this separately for the `#base` keyword. But it seems there is only the option `vscode-vdf.vdf.format.quotes`.

**Comment by qkeitoe** [comment] 2024-07-10 21:28
Btw, is the budhud formatter publicly available for use?

**Comment by rbjaxter** [comment] 2024-07-10 22:21
Yep! You can find it on Revan's Github here: https://github.com/cooolbros/vscode-budhud-formatter

I can't remember exactly why he had to separate it from his main extension but I think it was ultimately because I am difficult lmao

**Comment by qkeitoe** [comment] 2024-07-10 22:28
![image](https://github.com/rbjaxter/budhud/assets/66339491/2e52cfa9-6fb5-46d6-ad7c-01d8074a6990)

Couldn't find it on Revan's GitHub manually, so I assume this repo is private (?)

**Comment by cooolbros** [comment] 2024-07-11 00:36
Currently there is no option for excluding #base from the quotes formatting rules, but quoted #base is valid in TF2. Looking at the above screenshot I think the problem is in the Budhud Compiler.

vscode-budhud-formatter is private because it is a temporary solution as in future the formatter might not need to rely on VSCode.

Here is the vscode-budhud-formatter `.vsix`, Github doesnt allow the file so it will need to be renamed after download

[vscode-budhud-formatter-0.0.2.zip](https://github.com/user-attachments/files/16170121/vscode-budhud-formatter-0.0.2.zip)

**Comment by rbjaxter** [comment] 2024-07-12 20:53
Good to know. It's been a while since I've reached out to @Abrahamic-God regarding the compiler, so I'm not sure if it'd be something he could look into. If it was, @qkeitoe's second message shows best what's happening (second screenshot being correct, whereas the first is adding #base as though it's a whole new panel for the file).

In the mean time, I'll just try to keep that in mind and not use quotes around any #base includes. The rest of my hud still uses `#base` instead of `"#base"`, so it shouldn't be too huge of an issue.

**Comment by rbjaxter** [comment] 2024-07-14 22:34
other than the compiler issue, I believe this should be all good to go now so I'll close the issue

**Closed by rbjaxter** 2024-07-14 22:34 UTC
Labels: HUD Issue, Complete
